# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16a2c7bbf4c005bcdaff98ed865caeff00cd2affb77e021674989bdf371007796a9d600e1d6da7303f8f18b48932421574ede2f10b786085801d3ef46d694468

test:
  secret_key_base: 8bff43cb688fcce91e6812a38a48ae4068498f4239dc8ed5badc2a55138703b9b44100ae52d8767c5d5d6ba4c150f18206508f72ba218ce60b01938765fdca49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
